export interface P6rIdentityError {
  readonly code: "unavailable" | "unauthenticated" | "unsupported" | "incompatible" | "invalid-input" | "not-found" | "ambiguous" | "stale-owner" | "stale-context" | "conflict" | "cancelled" | "disposed" | "limit-exceeded" | "invalid-operation" | "expired";
  readonly message: string;
  readonly retry: "never" | "after-refresh" | "after-reconnect" | "same-operation";
}

export type P6rResult<T> = { readonly ok: true; readonly value: T } | { readonly ok: false; readonly error: P6rIdentityError };
export interface P6rProfilePresentation { readonly avatarUrl: string | null; readonly displayName: string; readonly handle: string | null; }
export interface P6rPersonReference { readonly issuer: string; readonly key: string; readonly kind: "person"; readonly subject: string; }
export interface P6rProviderConfiguration { readonly boundaryId: string; readonly credentials: readonly { readonly field: string; readonly name: string; readonly source: "header" | "cookie" }[]; readonly ingressIds: readonly string[]; readonly pluginId: string; readonly resolver: { readonly maxSessionAgeMs: number; readonly timeoutMs: number }; readonly version: 1; }
export interface P6rProviderEvidence { readonly configuration: P6rProviderConfiguration; readonly credentials: readonly { readonly name: string; readonly value: string }[]; readonly deadlineAt: number; readonly ingress: { readonly authenticatedPeer: string | null; readonly id: string | null; readonly kind: "owned-proxy" | "local" | "unverified" }; readonly request: { readonly authority: string; readonly method: string; readonly pathname: string; readonly receivedAt: number; readonly transport: "http" | "websocket" }; readonly signal: AbortSignal; readonly version: 1; }
export type P6rProviderResolution = { readonly issuer: string; readonly presentation: P6rProfilePresentation; readonly status: "resolved"; readonly subject: string; readonly validUntil: number } | { readonly status: "not-applicable" } | { readonly reason: string; readonly status: "rejected" | "unavailable" };
export interface P6rProviderDirectoryRecord { readonly issuer: string; readonly presentation: P6rProfilePresentation; readonly status: "current" | "historical"; readonly subject: string; }
export interface P6rProviderDirectorySource { readonly directory?: (input: { readonly cursor?: string; readonly history: "current" | "include-historical"; readonly limit: number; readonly query: string }, options?: { readonly signal?: AbortSignal }) => Promise<P6rResult<{ readonly nextCursor: string | null; readonly records: readonly P6rProviderDirectoryRecord[]; readonly revision: string }>>; readonly generation: string; readonly issuers: readonly string[]; readonly lookup?: (subjects: readonly { readonly issuer: string; readonly subject: string }[], options?: { readonly signal?: AbortSignal }) => Promise<P6rResult<{ readonly records: readonly { readonly issuer: string; readonly record: P6rProviderDirectoryRecord | null; readonly subject: string }[]; readonly revision: string }>>; person(issuer: string, subject: string): P6rResult<P6rPersonReference>; }
export interface P6rForkIdentityProvider { readonly issuers: readonly string[]; readonly resolve: (evidence: P6rProviderEvidence) => Promise<P6rProviderResolution>; readonly validateReadiness?: (input: { readonly configuration: Readonly<P6rProviderConfiguration>; readonly deadlineAt: number; readonly generation: string; readonly signal: AbortSignal }) => Promise<P6rResult<void>>; readonly directory?: P6rProviderDirectorySource["directory"]; readonly lookup?: P6rProviderDirectorySource["lookup"]; }
export interface P6rForkProviderRegistration { readonly configuration: Readonly<P6rProviderConfiguration>; dispose(): void; readonly generation: string; getStatus(): "staged" | "active" | "retired"; invalidate(change: { readonly kind: "authentication"; readonly subjects?: readonly { readonly issuer: string; readonly subject: string }[] } | { readonly kind: "directory"; readonly revision: string }): P6rResult<void>; person(issuer: string, subject: string): P6rResult<P6rPersonReference>; readonly signal: AbortSignal; subscribe(listener: (status: "staged" | "active" | "retired") => void): () => void; }
export interface P6rPreparedProvider { readonly configuration: Readonly<P6rProviderConfiguration>; readonly generation: string; readonly pluginId: string; readonly registration: P6rForkProviderRegistration; }
export type P6rProviderInvalidation = { readonly epoch: number; readonly generation: string; readonly kind: "authentication"; readonly subjects?: readonly { readonly issuer: string; readonly subject: string }[] } | { readonly generation: string; readonly kind: "directory"; } | { readonly epoch: number; readonly generation: string; readonly kind: "retired"; };
export interface P6rProviderRegistry { directorySources(): readonly P6rProviderDirectorySource[]; notifyPublished(candidate: P6rPreparedProvider): void; prepare(input: { readonly configuration: P6rProviderConfiguration; readonly deadlineAt: number; readonly generation: string; readonly provider: P6rForkIdentityProvider }): Promise<P6rResult<P6rPreparedProvider>>; publish(candidate: P6rPreparedProvider): P6rResult<{ readonly active: P6rPreparedProvider; readonly predecessor: P6rPreparedProvider | null }>; resolve(evidence: P6rProviderEvidence): Promise<P6rProviderResolution>; retire(candidate: P6rPreparedProvider): void; subscribeInvalidations(listener: (event: P6rProviderInvalidation) => void): () => void; }
